eventex/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.core.views',
    url(r'^$', 'homepage', name='homepage'),
    url(r'^palestrantes/(?P<slug>[\w-]+)/$', 'speaker_detail', name='speaker_detail'),
    url(r'^palestras/$', 'talk_list', name='talk_list'),

)

eventex/subscriptions/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views',
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'detail', name='detail'),
)

eventex/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    url(r'', include('eventex.core.urls', namespace='core')),

    url(r'^admin/', include(admin.site.urls)),
)

eventex/core/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from eventex.core.managers import KindContactManager, PeriodManager


class Speaker(models.Model):
    name = models.CharField(_(u'Nome'), max_length=255)
    slug = models.SlugField(_(u'Slug'))
    url = models.URLField(_(u'URL'))
    description = models.TextField(_(u'Descrição'), blank=True)


    class Meta:
        verbose_name = _(u'palestrante')
        verbose_name_plural = _(u'palestrantes')


    def __unicode__(self):
        return self.name


    @models.permalink
    def get_absolute_url(self):
        return ('core:speaker_detail', (), {'slug': self.slug})

class Contact(models.Model):
    KINDS = (
        ('P', _('Telefone')),
        ('E', _('Email')),
        ('F', _('Fax')),
    )

    speaker = models.ForeignKey('Speaker', verbose_name=_(u'palestrante'))
    kind = models.CharField(_(u'Tipo'), max_length=1, choices=KINDS)
    value = models.CharField(_(u'Valor'), max_length=255)

    objects = models.Manager()
    emails = KindContactManager('E')
    phones = KindContactManager('P')
    faxes = KindContactManager('F')


    def __unicode__(self):
        return self.value

class Talk(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.TimeField(blank=True)
    speakers = models.ManyToManyField('Speaker', verbose_name=_(u'palestrante'))


    class Meta:
        verbose_name = _(u'palestra')
        verbose_name_plural = _(u'palestras')

    objects = PeriodManager()


    def __unicode__(self):
        return self.title
    

    def get_absolute_url(self):
        return '/palestras/%d/' % self.pk


class Course(Talk):
    slots = models.IntegerField()
    notes = models.TextField()

    objects = PeriodManager()

eventex/subscriptions/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Subscription(models.Model):
    name = models.CharField(_('nome'), max_length=100)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    email = models.EmailField(_('email'), blank=True)
    phone = models.CharField(_('telefone'), max_length=20, blank=True)
    created_at = models.DateTimeField(_('criado em'), auto_now_add=True)
    paid = models.BooleanField(_('Pago'))

    class Meta:
        ordering = ['created_at']
        verbose_name = _(u'inscrição')
        verbose_name_plural = _(u'inscrições')

    def __unicode__(self):
        return self.name

eventex/subscriptions/forms.py
# coding: utf-8
from django import forms
from django.forms import TextInput
from django.forms import MultiWidget, MultiValueField
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.core.validators import EMPTY_VALUES
from eventex.subscriptions.models import Subscription


def CPFValidator(value):
    if not value.isdigit():
        raise ValidationError(_(u'CPF deve conter apenas números'))
    if len(value) != 11:
        raise ValidationError(_(u'CPF deve conter 11 dígitos'))
 

class PhoneWidget(forms.MultiWidget):
    def __init__(self, **kwargs):
        widgets = (forms.TextInput(attrs={'class': 'form-control'}),
                   forms.TextInput(attrs={'class': 'form-control'}))
        super(PhoneWidget, self).__init__(widgets, **kwargs)

    def decompress(self, value):
        if not value:
            return [None, None]
        return value.split('-')


class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (forms.IntegerField(),
                  forms.IntegerField())
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''
        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'DDD inválido.'))
        if data_list[1] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'Número inválido.'))
        return '%s-%s' % tuple(data_list)



class SubscriptionForm(forms.ModelForm):
    phone = PhoneField(label=_('Telefone'), required=False)

    class Meta:
        model = Subscription
        fields = ('name', 'cpf', 'email', 'phone')
        exclude = ('paid',)
        widgets = {'name': TextInput(attrs={'class': 'form-control'}),
                   'cpf': TextInput(attrs={'class': 'form-control'}),
                   'email': TextInput(attrs={'class': 'form-control'})}

    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)
        self.fields['cpf'].validators.append(CPFValidator)


    def clean_name(self):
        name = self.cleaned_data['name']
        words = name.split()
        for index, word in enumerate(words):
            words[index] = word.capitalize()
        capitalized_name = ' '.join(words)
        return capitalized_name


    def clean(self):
        super(SubscriptionForm, self).clean()

        if not self.cleaned_data.get('email') and \
           not self.cleaned_data.get('phone'):
            raise ValidationError(_(u'Informe seu email ou telefone'))
        return self.cleaned_data

eventex/core/views.py
# coding: utf-8
from datetime import time
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from eventex.core.models import Speaker, Talk


def homepage(request):
    return render(request, 'index.html')
    

def speaker_detail(request, slug):
	speaker = get_object_or_404(Speaker, slug=slug)
	context = {'speaker': speaker}
	return render(request, 'core/speaker_detail.html', context)


def talk_list(request):
	context = {
		'morning_talks': Talk.objects.at_morning(),
		'afternoon_talks': Talk.objects.at_afternoon()
	}
	return render(request, 'core/talk_list.html', context)

eventex/subscriptions/views.py
# coding: utf-8
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from eventex.subscriptions.forms import SubscriptionForm
from eventex.subscriptions.models import Subscription


def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)


def new(request):
    return render(request, 'subscriptions/subscription_form.html',
                  {'form': SubscriptionForm()})


def create(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return render(request, 'subscriptions/subscription_form.html',
                      {'form': form})

    obj = form.save()
    return HttpResponseRedirect('/inscricao/%d/' % obj.pk)


def detail(request, pk):
    subscription = get_object_or_404(Subscription, pk=pk)
    return render(request, 'subscriptions/subscription_detail.html',
                  {'subscription': subscription})

eventex/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EventeX!</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ STATIC_URL }}assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}assets/css/sticky-footer.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}assets/css/justified-nav.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Patrick+Hand' rel='stylesheet' type='text/css'>

    <style>
    body {background: url({{ STATIC_URL }}assets/img/bg/diamond_upholstery.png) center fixed;}
    .fontelogo {font-family: 'Patrick Hand', cursive; font-size: 120px;}
    #footer {background-color: rgb(64,81,117);}
    #footer p {color: #FFF;}
    </style>

</head>

<body>

    <div id="wrap">

        <div class="container">

                {% block content %}

                {% endblock content %}

        </div><!-- /container -->
    </div><!-- /wrap -->

    <div id="footer">

        <div class="container">
            <p class="text-muted credit">Para dúvidas e mais informações <a href="#"><b>kind76@gmail.com</b></a>.</p>
        </div><!-- /container -->

    </div><!-- /footer -->

</body>
</html>

eventex/core/templates/core/speaker_detail.html
{% extends 'base.html' %}

{% block content %}
	<h4><a href="{{ speaker.url }}"> {{ speaker.name }}</a></h4>
	<p>{{ speaker.description }}</p>
{% endblock content %}

eventex/core/templates/core/talk_list.html
{% extends 'base.html' %}

{% block content %}

<h3>Manhã</h3>
{% for talk in morning_talks %}
    {% include 'core/talk_list_snippet.html' %}
{% empty %}
    <p>Não existem palestras durante a manhã</p>
{% endfor %}

<h3>Tarde</h3>
{% for talk in afternoon_talks %}
    {% include 'core/talk_list_snippet.html' %}
{% empty %}
    <p>Não existem palestras durante a tarde</p>
{% endfor %}

{% endblock content %}

eventex/core/templates/core/talk_list_snippet.html
<div class="palestra">
	<h4>
		<a href="{{ talk.get_absolute_url }}">
			{{ talk.start_time }} - {{talk.title }}
		</a>
	</h4>
	{% for speaker in talk.speakers.all %}
	<h5>
		<a href="{{ speaker.get_absolute_url }}" title="{{ speaker.description|truncatewords:30 }}">
			{{ speaker.name }}
		</a>
	</h5>
	{% endfor %}
	<p>{{ talk.description }}</p>
</div>

eventex/core/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <h1>Bem-vindo ao <span class="fontelogo">EventeX!</span></h1>
    <br>
    <p class="lead">O evento mais sensacional do ano depois do Dev in Rio! Você não pode perder esta oportunidade!</p>
    <p><a class="btn btn-lg btn-primary" href="{% url 'subscriptions:subscribe' %}">Inscrições abertas! <strong>Clique aqui</strong>!</a></p>
</div>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="alert alert-success">
    <h1>Parabéns <strong>{{ subscription.name }}</strong>!</h1>

    <span>Sua inscrição foi realizada em {{ subscription.created_at|date:"d/m/Y" }}.</span>

    <span>Em breve entraremos em contato pelo
        {% if subscription.phone %}
        telefone {{ subscription.phone }}.
        {% else %}
        email {{ subscription.email }}.
        {% endif %}
    </span>
    <br>
    <br>
    <a class="btn btn-info btn-lg btn-block" href="/">
        <span class="glyphicon glyphicon-home"></span> <strong>Voltar para página principal</strong>
    </a>
</div>
{% endblock content%}

eventex/subscriptions/templates/subscriptions/subscription_form.html
{% extends 'base.html' %}

{% block content %}
<div class="well">
<form role="form" action="." method="POST">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
        {{ form.non_field_errors }}
    </div>
    {% endif%}
    <fieldset>

        <!-- Form Name -->
        <legend>Formulário de inscrição</legend>

        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" class="control-label">{{ form.name.label }}</label>
            <div class="controls">
            {{ form.name }}
            </div>
            {{ form.name.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.cpf.id_for_label }}" class="control-label">{{ form.cpf.label }}</label>
            <div class="controls">
            {{ form.cpf }}
            </div>
            {{ form.cpf.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.email.id_for_label }}" class="control-label">{{ form.email.label }}</label>
            <div class="input-group">
                <span class="input-group-addon">@</span>
            {{ form.email }}
            </div>
            {{ form.email.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.phone.id_for_label }}" class="control-label">{{ form.phone.label }}</label>
            <div class="controls">
            {{ form.phone }}
            </div>
            {{ form.phone.errors }}
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="control-label"></label>
            <div class="controls">
                <button id="enviar" name="enviar" class="btn btn-lg btn-success">Enviar!</button>
            </div>
        </div>

    </fieldset>
</form>
</div>
{% endblock content %}